name: ci-cd

on: [push, pull_request]

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v2

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Package
      run: poetry install


    