name: CI/CD

on: [push, pull_request]

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v3

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install Package
      run: poetry install

  cd:
    name: Release & Publish
    needs: ci
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: write    

    steps:
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Check-out repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Build distribution with Poetry
      run: poetry build

    - name: Extract latest changelog
      id: changelog
      run: |
        export CHANGELOG=$(awk '/^## /{i++} i==3{exit} i==1{print} i==2{print}' CHANGELOG.md | tail -n +2)
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Get version from pyproject.toml
      id: version
      run: |
        echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}

    - name: Test install from TestPyPI
      run: |
        python -m venv testenv
        source testenv/bin/activate
        pip install --upgrade pip
        pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple kedrogen
        kedrogen --version
        deactivate

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v${{ steps.version.outputs.version }}
        name: v${{ steps.version.outputs.version }}
        body: ${{ steps.changelog.outputs.changelog }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}


    